export const DEFAULT_FUNNEL = {
  brandName: 'Emma · accès privé',
  creatorUsername: '@emma_a_configurer',
  paymentLink: 'https://buy.stripe.com/remplace-moi',
  proofChannelLink: 'https://t.me/remplace-moi',
  vipInviteLink: '',
  priceText: '35 € · une seule formule · tout compris · sans engagement',
  claimReply: 'J’ai bien reçu ta demande 💌 Je ne valide rien sur une capture seule. Écris-moi ici pendant que je vérifie le paiement :',
  verifiedReply: 'C’est bon, ton paiement est confirmé 💗 Bienvenue dans mon espace VIP.',
  adultNotice: 'Réservé aux personnes majeures (18+).',
  steps: [
    {
      id: 'welcome',
      active: true,
      title: 'Bienvenue chez Emma',
      text: '<b>Coucou, moi c’est Emma 💗</b>\n\nJ’ai préparé ce petit parcours pour te montrer ce qui se cache dans mon VIP… et ce qu’on pourrait partager tous les deux.\n\n<i>Tu me suis ?</i>',
      mediaType: 'photo',
      media: '/media/portrait-emma.jpg',
      buttons: [{ label: 'Je te suis 💌', action: 'next', target: 'why-bot' }],
    },
    {
      id: 'why-bot',
      active: true,
      title: 'Pourquoi ce bot',
      text: '<b>Pourquoi ce petit bot ? 😅</b>\n\nJe recevais trop de messages de mecs qui parlaient pendant des heures, réclamaient des photos, puis disparaissaient. Je suis humaine, mon temps et mon attention comptent aussi.\n\nAlors je garde mon énergie pour ceux qui ont vraiment envie d’entrer dans mon univers.',
      mediaType: 'photo',
      media: '/media/portrait-emma-2.jpg',
      buttons: [{ label: 'Montre-moi un aperçu 👀', action: 'next', target: 'teaser-hook-one' }],
    },
    {
      id: 'teaser-hook-one',
      active: true,
      title: 'Un tout petit aperçu',
      text: '<b>Je vais te montrer juste un petit bout de mon univers… 👀</b>\n\nIci, je reste encore sage. La suite, je la garde pour ceux qui ont vraiment envie de venir me connaître.\n\n<i>Tu veux que je t’en montre un peu plus ?</i>',
      mediaType: 'photo',
      media: '/media/apercu-emma.jpg',
      buttons: [{ label: 'Oui, encore un peu 🙈', action: 'next', target: 'teaser-hook-two' }],
    },
    {
      id: 'teaser-hook-two',
      active: true,
      title: 'La suite est plus privée',
      text: '<b>Imagine recevoir une petite attention rien que pour toi… 🙈</b>\n\nUne photo qui arrive au bon moment. Un message le soir. Puis notre délire qui devient de plus en plus naturel.\n\n<b>Petit truc important :</b> si tu m’écris en privé, fais-le avec une vraie intention (une question précise sur le VIP) ou après paiement avec ton screen. Sinon je ne réponds pas.\n\n<i>Et là, tu n’as encore vu que l’entrée.</i>',
      mediaType: 'photo',
      media: '/media/apercu-lingerie-emma-2.jpg',
      buttons: [{ label: 'Explique-moi ton VIP 💗', action: 'next', target: 'vip-explained' }],
    },
    {
      id: 'vip-explained',
      active: true,
      title: 'Le VIP, c’est quoi ?',
      text: '<b>Le VIP, c’est un abonnement à 35 €, sans engagement.</b>\n\n🔐 Tu entres dans mon canal Telegram privé\n🔞 Tu découvres mes photos très explicites et mes sextapes\n💌 Tu peux venir discuter et échanger avec moi en privé\n\n<i>Une seule formule. Tout est compris.</i>',
      mediaType: 'photo',
      media: '/media/miroir-emma-1.jpg',
      buttons: [
        { label: 'Avant-goût 1 👀', action: 'next', target: 'weekly-content' },
        { label: 'Avant-goût 2 🔥', action: 'next', target: 'teaser-two' },
        { label: 'Découvrir la suite 💗', action: 'next', target: 'grade-one' },
      ],
    },
    {
      id: 'weekly-content',
      active: false,
      title: 'Avant-goût vidéo 1 · à compléter',
      text: '<b>Chaque semaine dans le canal privé 👇</b>\n\n🔞 Photos et nudes très explicites : À COMPLÉTER\n🎥 Sextapes solo ou accompagnée : À COMPLÉTER\n💌 Contenus inspirés de vos fantasmes : À COMPLÉTER\n\n<i>Je garde aussi quelques surprises pour les membres 💗</i>',
      mediaType: 'video',
      media: '',
      buttons: [{ label: 'Et pour discuter avec toi ?', action: 'next', target: 'grade-one' }],
    },
    {
      id: 'grade-one',
      active: true,
      title: 'Ce qui t’attend',
      text: '<b>Ce qui t’attend derrière le bouton 💗</b>\n\nTu entres dans mon petit jardin secret, tu découvres tout ce que je réserve au canal et tu peux venir me parler en privé.\n\nOn apprend à se connaître doucement, on partage nos journées… puis on voit où notre complicité nous emmène 😇',
      mediaType: 'photo',
      media: '/media/apercu-emma.jpg',
      buttons: [{ label: 'Pourquoi 35 € ?', action: 'next', target: 'upgrades' }],
    },
    {
      id: 'upgrades',
      active: true,
      title: 'Pourquoi 35 € ?',
      text: '<b>Pourquoi 35 € ?</b>\n\nTu vois parfois un abonnement à 10 € qui semble intéressant… puis :\n📸 une photo à 20 €\n🎥 une vidéo à 50 €\n🔥 une sextape à 100 €\n\nAu final, ça peut revenir à plusieurs centaines d’euros.\n\n<b>Avec moi : 35 €, tout compris et en illimité pendant ton accès.</b>',
      mediaType: 'photo',
      media: '/media/apercu-lingerie-emma-2.jpg',
      buttons: [{ label: 'Et entre nous deux ?', action: 'next', target: 'private-exchanges' }],
    },
    {
      id: 'private-exchanges',
      active: true,
      title: 'Rien que toi et moi',
      text: '<b>Ce que tu trouveras dans mon VIP 🔥</b>\n\n📸 Des nudes très explicites : des photos de moi en lingerie en dentelle, entièrement nue et très sexy, ainsi que des photos avec mes copines.\n\n🎥 J’ai aussi des vidéos solo où je me fais du bien et où je jouis très fort, mais également des sextapes avec des hommes ou des femmes.\n\n🎭 Je peux être ta maîtresse comme ta soumise, et je suis ouverte à réaliser d’autres types de contenus personnalisés.\n\n<b>Tout est compris</b>, toujours entre adultes consentants.',
      mediaType: 'photo',
      media: '/media/miroir-emma-2.jpg',
      buttons: [{ label: 'Fais-moi rêver 🙈', action: 'next', target: 'surprises' }],
    },
    {
      id: 'surprises',
      active: true,
      title: 'Imagine un peu…',
      text: '<b>Imagine un peu… 🙈</b>\n\nTu rentres chez toi, tu ouvres Telegram et tu découvres ce que j’ai posté dans le canal. Plus tard, on se retrouve en privé, on parle de ta journée, on se taquine… et parfois une petite surprise arrive juste pour toi.\n\n<i>C’est cette bulle à nous que j’ai envie de créer. Une complicité qui continue bien après avoir regardé les photos.</i>',
      mediaType: 'photo',
      media: '/media/apercu-bikini-emma.jpg',
      buttons: [{ label: 'Je veux voir les avis', action: 'next', target: 'trust' }],
    },
    {
      id: 'trust',
      active: true,
      title: 'Ne me crois pas sur parole',
      text: '<b>Ne me crois pas seulement sur parole 💗</b>\n\nRegarde les avis dans mon canal de preuves. Tu verras vite que je suis une vraie petite ange quand on me traite bien.\n\nLe VIP est à <b>35 €, sans engagement</b>. Tu arrêtes quand tu veux. Le paiement passe par Stripe et je ne te demanderai jamais tes données bancaires dans Telegram.',
      mediaType: 'photo',
      media: '/media/portrait-emma-2.jpg',
      buttons: [
        { label: 'Voir les preuves', action: 'proof', target: '' },
        { label: 'J’ai envie de te rejoindre', action: 'next', target: 'join' },
      ],
    },
    {
      id: 'join',
      active: true,
      title: 'Je te garde une place ?',
      text: '<b>Je te garde une place ? 💗</b>\n\n35 € pour entrer dans mon canal, profiter de tout mon contenu adulte explicite en illimité, sextapes comprises, et vivre cette complicité avec moi. Le tout sans engagement.\n\nAprès le paiement, reviens ici et appuie sur « J’ai payé ». Je vérifie et je t’envoie ton accès.',
      mediaType: 'none',
      media: '',
      buttons: [
        { label: 'Rejoindre mon VIP · 35 €', action: 'next', target: 'payment-howto' },
        { label: 'Voir les preuves', action: 'proof', target: '' },
        { label: 'J’ai payé', action: 'claim', target: '' },
        { label: 'M’écrire directement', action: 'contact', target: '' },
      ],
    },
    {
      id: 'payment-howto',
      active: true,
      title: 'Après le paiement',
      text: '<b>Après le paiement :</b>\n\n1) Ouvre la page Stripe\n2) Fais le paiement\n3) Envoie-moi ton screen à @emmattvv\n4) Reviens ici et appuie sur « J’ai payé »\n\n<i>Si tu m’écris en privé sans screen, sans vraie intention, ou sans vraie question sur le VIP, je ne réponds pas.</i>',
      mediaType: 'none',
      media: '',
      buttons: [
        { label: 'Ouvrir la page Stripe', action: 'payment', target: '' },
        { label: 'Envoyer mon screen à @emmattvv', action: 'url', target: 'https://t.me/emmattvv' },
        { label: 'J’ai payé', action: 'claim', target: '' },
        { label: 'Retour', action: 'next', target: 'join' },
      ],
    },
    {
      id: 'teaser-two',
      active: false,
      title: 'Avant-goût vidéo 2 · à importer',
      text: '<b>Tu en veux encore un peu ? 🔥</b>\n\nJe te laisse ce deuxième avant-goût… juste assez pour faire travailler ton imagination.\n\n<i>Le reste nous attend dans mon petit coin privé.</i>',
      mediaType: 'video',
      media: '',
      buttons: [
        { label: 'Découvrir la suite 💗', action: 'next', target: 'grade-one' },
        { label: 'Revenir aux aperçus', action: 'next', target: 'vip-explained' },
      ],
    },
  ],
};

export function initialState() {
  return {
    version: 1,
    config: structuredClone(DEFAULT_FUNNEL),
    leads: {},
    jobs: [],
    telegramOffset: 0,
    processedStripeEvents: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
